### ISSUE TITLE
implement Healthy threshold 

### ISSUE THREAD

**Issue by nbari** [nbari/epazote#2]
Implement Healthy and Unhealthy thresholds

**Comment by nbari** [comment]
```
      # Healthy/Unhealthy threshold
        threshold:
            healthy: 2 # consecutive successes
            unhealthy: 2 # consecutive failures

```
